// Code generated by oapix-gen. DO NOT EDIT.
package productapi

import (
	"time"
)

type CreateProductRequest struct {
	Price       float64 `json:"price"`
	Category    string  `json:"category"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

type Error struct {
	Code    *string     `json:"code,omitempty"`
	Details interface{} `json:"details,omitempty"`
	Message *string     `json:"message,omitempty"`
}

type Pagination struct {
	Limit      *int64 `json:"limit,omitempty"`
	Page       *int64 `json:"page,omitempty"`
	TotalItems *int64 `json:"totalItems,omitempty"`
	TotalPages *int64 `json:"totalPages,omitempty"`
}

type Product struct {
	// Unique product identifier
	ID string `json:"id"`
	// Whether the product is in stock
	InStock *bool `json:"inStock,omitempty"`
	// Product name
	Name string `json:"name"`
	// Product price
	Price float64 `json:"price"`
	// Product category
	Category *string `json:"category,omitempty"`
	// Product description
	Description *string `json:"description,omitempty"`
}

type Review struct {
	ProductID *string    `json:"productId,omitempty"`
	Rating    *int64     `json:"rating,omitempty"`
	Comment   *string    `json:"comment,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ID        *string    `json:"id,omitempty"`
}

type UpdateProductRequest struct {
	Description *string  `json:"description,omitempty"`
	InStock     *bool    `json:"inStock,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Category    *string  `json:"category,omitempty"`
}
