openapi: 3.0.0
info:
  title: Multi-Response Example API
  version: 1.0.0
  description: Demonstrates multiple response types handling

paths:
  /assets/{assetId}:
    post:
      operationId: createAsset
      summary: Create or update an asset
      parameters:
        - name: assetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetInput'
      responses:
        "200":
          description: Asset updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentNodeTransport'
        "201":
          description: Asset created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentNodeTransport'
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FrontendHandledBackendError'
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExceptionReference'

  /users/{userId}:
    get:
      operationId: getUser
      summary: Get user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionReference'

components:
  schemas:
    AssetInput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        metadata:
          type: object
      required:
        - name
        - type

    ContentNodeTransport:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        metadata:
          type: object

    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        active:
          type: boolean

    FrontendHandledBackendError:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
        details:
          type: object

    NotFoundError:
      type: object
      properties:
        message:
          type: string
        resource:
          type: string
        id:
          type: string

    ExceptionReference:
      type: object
      properties:
        reference:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time